---
# tasks file for newrelic_wsgi

- name: record variables supplied by environment file 
  shell: echo "{{ env_vars }}"
  sudo: yes

#    https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-admin-script
- name: create directory for newrelic config
  file:
    dest=/opt/newrelic/
    mode=755
    state=directory
  sudo: yes

- name: create directory for newrelic logging accessible to apache user and newrelic
  file:
    dest={{newrelic_agentlog_path}}
    mode=755
    owner=apache
    group=apache
    state=directory
  sudo: yes
 
- name: pip install newrelic
  pip: name=newrelic
       extra_args='--install-option="--install-scripts=/usr/bin"'
  sudo: yes

- name: genetate newrelic.ini file
  sudo: yes
  template:
    src: /templates/newrelic.ini.j2
    dest: {{ newrelic_ini_file }}
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache    

- name: make empty log file with right permissions 
  file:
    dest={{newrelic_agentlog_file}}
    mode=660
    owner=apache
    group=apache
    state=touch
  sudo: yes

- name: add agent config to the wsgi file
  lineinfile: dest={{wsgi_scriptfile}} state=present line="newrelic.agent.initialize('{{newrelic_ini_file}}')" insertbefore=BOF
  sudo: yes
  notify:
    - restart apache    

- name: import newrelic to wsgi
  lineinfile: dest={{wsgi_scriptfile}} state=present line="import newrelic.agent" insertbefore=BOF
  sudo: yes
  notify:
    - restart apache    

